---
application:
    name: "fit4u"
    project: "fit4u"
    organization: "QoveryCommunity"
    publicly_accessible: true
    port: 3000
routers:
    - name: "main-fit4u"
      routes:
          - application_name: "fit4u"
            paths:
                - "/*"
